// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: app/v1/puzzle.proto

package appv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Puzzle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Question string `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answer   string `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *Puzzle) Reset() {
	*x = Puzzle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_v1_puzzle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Puzzle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Puzzle) ProtoMessage() {}

func (x *Puzzle) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_puzzle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Puzzle.ProtoReflect.Descriptor instead.
func (*Puzzle) Descriptor() ([]byte, []int) {
	return file_app_v1_puzzle_proto_rawDescGZIP(), []int{0}
}

func (x *Puzzle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Puzzle) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Puzzle) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type ListPuzzlesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListPuzzlesRequest) Reset() {
	*x = ListPuzzlesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_v1_puzzle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPuzzlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPuzzlesRequest) ProtoMessage() {}

func (x *ListPuzzlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_puzzle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPuzzlesRequest.ProtoReflect.Descriptor instead.
func (*ListPuzzlesRequest) Descriptor() ([]byte, []int) {
	return file_app_v1_puzzle_proto_rawDescGZIP(), []int{1}
}

func (x *ListPuzzlesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListPuzzlesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Puzzles []*Puzzle `protobuf:"bytes,1,rep,name=puzzles,proto3" json:"puzzles,omitempty"`
}

func (x *ListPuzzlesResponse) Reset() {
	*x = ListPuzzlesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_v1_puzzle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPuzzlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPuzzlesResponse) ProtoMessage() {}

func (x *ListPuzzlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_v1_puzzle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPuzzlesResponse.ProtoReflect.Descriptor instead.
func (*ListPuzzlesResponse) Descriptor() ([]byte, []int) {
	return file_app_v1_puzzle_proto_rawDescGZIP(), []int{2}
}

func (x *ListPuzzlesResponse) GetPuzzles() []*Puzzle {
	if x != nil {
		return x.Puzzles
	}
	return nil
}

var File_app_v1_puzzle_proto protoreflect.FileDescriptor

var file_app_v1_puzzle_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x22, 0x4c, 0x0a,
	0x06, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x12, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x3f, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28,
	0x0a, 0x07, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x52,
	0x07, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x73, 0x42, 0x60, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0c, 0x61, 0x70, 0x70, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x70,
	0x70, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x41, 0x70, 0x70, 0x2e,
	0x56, 0x31, 0xca, 0x02, 0x06, 0x41, 0x70, 0x70, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x12, 0x41, 0x70,
	0x70, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x07, 0x41, 0x70, 0x70, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_app_v1_puzzle_proto_rawDescOnce sync.Once
	file_app_v1_puzzle_proto_rawDescData = file_app_v1_puzzle_proto_rawDesc
)

func file_app_v1_puzzle_proto_rawDescGZIP() []byte {
	file_app_v1_puzzle_proto_rawDescOnce.Do(func() {
		file_app_v1_puzzle_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_v1_puzzle_proto_rawDescData)
	})
	return file_app_v1_puzzle_proto_rawDescData
}

var file_app_v1_puzzle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_app_v1_puzzle_proto_goTypes = []interface{}{
	(*Puzzle)(nil),              // 0: app.v1.Puzzle
	(*ListPuzzlesRequest)(nil),  // 1: app.v1.ListPuzzlesRequest
	(*ListPuzzlesResponse)(nil), // 2: app.v1.ListPuzzlesResponse
}
var file_app_v1_puzzle_proto_depIdxs = []int32{
	0, // 0: app.v1.ListPuzzlesResponse.puzzles:type_name -> app.v1.Puzzle
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_v1_puzzle_proto_init() }
func file_app_v1_puzzle_proto_init() {
	if File_app_v1_puzzle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_v1_puzzle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Puzzle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_v1_puzzle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPuzzlesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_v1_puzzle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPuzzlesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_v1_puzzle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_v1_puzzle_proto_goTypes,
		DependencyIndexes: file_app_v1_puzzle_proto_depIdxs,
		MessageInfos:      file_app_v1_puzzle_proto_msgTypes,
	}.Build()
	File_app_v1_puzzle_proto = out.File
	file_app_v1_puzzle_proto_rawDesc = nil
	file_app_v1_puzzle_proto_goTypes = nil
	file_app_v1_puzzle_proto_depIdxs = nil
}
