name: native-ci

on:
  push:
    # paths:
    #   - 'native/**'
  pull_request:
    branches:
      - main
    paths:
      - 'native/**'

defaults:
  run:
    working-directory: ./native

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/flutter_setup
      - run: flutter build apk --release

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/flutter_setup
      - run: flutter analyze .

  # TODO テスト追加時に有効化
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/flutter_setup
  #     - run: flutter test