name: native-lint

on:
  push:
    paths:
      - 'native/**'
  pull_request:
    branches:
      - main
    paths:
      - 'native/**'

defaults:
  run:
    working-directory: ./native

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
    - name: Get Dependencies
      run: flutter pub get
    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: ${{ runner.os }}-pub-
    - name: Run Lint
      run: flutter analyze .

  # TODO テスト追加時に有効化
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Setup Flutter
  #     uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: '3.13.0'
  #   - name: Get Dependencies
  #     run: flutter pub get
  #   - name: Cache Flutter dependencies
  #     uses: actions/cache@v3
  #     with:
  #       path: ~/.pub-cache
  #       key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
  #       restore-keys: ${{ runner.os }}-pub-
  #   - name: Run Tests
  #     run: flutter test